[theme]
primaryColor = "#1a73e8"
backgroundColor = "#f9fafb"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#1f2937"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
